In [3]:
from __future__ import print_function
import torch

Import torch.

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[1.9349e-19, 4.5445e+30, 4.7429e+30],
        [7.1354e+31, 7.1118e-04, 1.7444e+28],
        [7.3909e+22, 4.5828e+30, 3.2483e+33],
        [1.9690e-19, 6.8589e+22, 1.3340e+31],
        [1.1708e-19, 7.2128e+22, 9.2216e+29]])


In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.8800, 0.8681, 0.5581],
        [0.9531, 0.7379, 0.2764],
        [0.5066, 0.0500, 0.2930],
        [0.0778, 0.6218, 0.2507],
        [0.6698, 0.2755, 0.5026]])


In [6]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.7801, -0.0849,  1.0849],
        [-0.2003, -2.0377, -0.5800],
        [ 0.8603,  0.1774, -0.4003],
        [-0.7218,  0.1895, -0.9955],
        [-0.1413,  0.6554,  1.1812]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5,3)
print(x + y)

tensor([[-0.5220, -0.0667,  1.9512],
        [ 0.4062, -1.2133, -0.5413],
        [ 1.6057,  0.9285,  0.0571],
        [-0.0841,  0.1996, -0.7912],
        [ 0.8262,  1.4061,  1.8097]])


In [12]:
print(torch.add(x,y))

tensor([[-0.5220, -0.0667,  1.9512],
        [ 0.4062, -1.2133, -0.5413],
        [ 1.6057,  0.9285,  0.0571],
        [-0.0841,  0.1996, -0.7912],
        [ 0.8262,  1.4061,  1.8097]])


In [13]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5220, -0.0667,  1.9512],
        [ 0.4062, -1.2133, -0.5413],
        [ 1.6057,  0.9285,  0.0571],
        [-0.0841,  0.1996, -0.7912],
        [ 0.8262,  1.4061,  1.8097]])


In [15]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.5220, -0.0667,  1.9512],
        [ 0.4062, -1.2133, -0.5413],
        [ 1.6057,  0.9285,  0.0571],
        [-0.0841,  0.1996, -0.7912],
        [ 0.8262,  1.4061,  1.8097]])


In [16]:
print(x[:,1])

tensor([-0.0849, -2.0377,  0.1774,  0.1895,  0.6554])


In [33]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
x, y, z

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


(tensor([[ 1.2405,  1.0387,  0.0306,  2.0813],
         [ 1.0303, -0.1440, -0.1740, -0.7129],
         [-1.0038,  1.1951, -0.5616, -1.9092],
         [ 0.5699,  0.6819, -0.6122,  0.2692]]),
 tensor([ 1.2405,  1.0387,  0.0306,  2.0813,  1.0303, -0.1440, -0.1740, -0.7129,
         -1.0038,  1.1951, -0.5616, -1.9092,  0.5699,  0.6819, -0.6122,  0.2692]),
 tensor([[ 1.2405,  1.0387,  0.0306,  2.0813,  1.0303, -0.1440, -0.1740, -0.7129],
         [-1.0038,  1.1951, -0.5616, -1.9092,  0.5699,  0.6819, -0.6122,  0.2692]]))

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1643])
-0.16433261334896088


###  NumPy Bridge  ###

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
torch.cuda.is_available()

False

# AUTOGRAD #

In [25]:
x

tensor([-0.1643])

In [26]:
x.type()

'torch.FloatTensor'

In [27]:
x.requires_grad

False

In [18]:
import torch

In [19]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [21]:
print(y.grad_fn)

In [22]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [23]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [24]:
out.backward()

In [25]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [26]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print (y)

tensor([  640.9883, -1082.9303,  -239.9085], grad_fn=<MulBackward0>)


In [27]:
v = torch.tensor([0.1, 1, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [28]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [29]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


# Neural Networks

In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channal, 6 output channals, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [35]:
x.size()

torch.Size([4, 4])

In [36]:
x.size()[1:]

torch.Size([4])

In [38]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 3, 3])


In [39]:
net.parameters()

<generator object Module.parameters at 0x000001329972EC00>

In [41]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.1537, -0.1421, -0.1391,  0.1361, -0.0011, -0.0038,  0.0318,  0.0970,
          0.1511,  0.0441]], grad_fn=<AddmmBackward>)


In [43]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [47]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.0235, grad_fn=<MseLossBackward>)


In [48]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

In [49]:
net.zero_grad()

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0114,  0.0366,  0.0166,  0.0032, -0.0031,  0.0010])


In [50]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [51]:
import torch.optim as optim

# create my optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in my training loop:
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()